[package]
name = "basisu_c_sys"
version = "0.9.0-dev"
edition = "2024"
description = "Rust binding and wrappers for Basis Universal C API"
repository.workspace = true
license.workspace = true
keywords = ["basis-universal", "ffi", "wasm-bindgen"]
include = [
  "CHANGELOG.md",
  "CMakeLists.txt",
  "README.md",
  "build.rs",
  "src/*.rs",
  "src/extra/*.rs",
  "vendored/basis_universal",
  "wasm_bindgen.rs",
  "write_cmake_args.rs"
]

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu", "wasm32-unknown-unknown"]
no-default-features = true
features = [
  "encoder",
  "serde",
  "extra",
]
rustdoc-args = ["--cfg", "docsrs"]

[[test]]
name = "transcoder"
path = "tests/transcoder.rs"
required-features = ["extra"]

[[test]]
name = "encoder"
path = "tests/encoder.rs"
required-features = ["encoder", "extra"]

[dependencies]
async-lock = { version = "3.4.2", default-features = false, optional = true }
bitflags = { version = "2.11.0", optional = true }
serde = {
  version = "1.0.228",
  default-features = false,
  features = [
    "derive",
  ],
  optional = true
}
thiserror = { version = "2.0.18", default-features = false, optional = true }

[dev-dependencies]
half = { version = "2.7.1", default-features = false }
image = {
  version = "0.25.10",
  default-features = false,
  features = [
    "exr",
    "jpeg",
    "webp",
  ]
}
insta = "1.47.2"

[build-dependencies]
bindgen = "0.72"
cc = { version = "1.2", features = ["parallel"] }
cmake = "0.1.58"

[target.wasm32-unknown-unknown.dependencies]
async-lock = { version = "3.4.2", default-features = false }
js-sys = "0.3"
wasm-bindgen = "0.2"
wasm-bindgen-futures = "0.4"

[features]
default = [
  "transcode_astc",
  "transcode_etc1s_bc4_5",
  "transcode_etc1s_bc7",
  "transcode_etc1s_etc2",
  "transcode_uastc",
  "transcode_uastc_hdr",
  "transcode_xuastc",
]
encoder = []
extra = [
  "dep:async-lock",
  "dep:bitflags",
  "dep:thiserror",
]
serde = ["dep:serde"]
transcode_astc = []
transcode_etc1s_bc1 = []
transcode_etc1s_bc3 = ["transcode_etc1s_bc1", "transcode_etc1s_bc4_5"]
transcode_etc1s_bc4_5 = []
transcode_etc1s_bc7 = []
transcode_etc1s_etc2 = []
transcode_uastc = []
transcode_uastc_hdr = []
transcode_xuastc = []
