[package]
name = "basisu_c_sys"
version = "0.7.1"
edition = "2024"
repository.workspace = true
license.workspace = true
description = "Rust binding and wrappers for the Basis Universal pure C API"
keywords = ["basis-universal", "ffi", "wasm-bindgen"]
include = [
  "vendor/basis_universal",
  "build.rs",
  "write_cmake_args.rs",
  "CMakeLists.txt",
  "README.md",
  "src/*.rs",
  "src/extra/*.rs",
]

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu", "wasm32-unknown-unknown"]
features = ["encoder", "serde", "extra"]

[features]
default = [
  "transcode_etc1s_bc4_5",
  "transcode_etc1s_bc7",
  "transcode_etc1s_etc2",
  "transcode_uastc",
  "transcode_uastc_hdr",
  "transcode_xuastc",
  "transcode_astc",
]
transcode_etc1s_bc3 = ["transcode_etc1s_bc1", "transcode_etc1s_bc4_5"]
transcode_etc1s_bc1 = []
transcode_etc1s_bc4_5 = []
transcode_etc1s_bc7 = []
transcode_etc1s_etc2 = []
transcode_uastc = []
transcode_uastc_hdr = []
transcode_xuastc = []
transcode_astc = []
encoder = []
extra = [
  "dep:wgpu-types",
  "dep:bytemuck",
  "dep:async-lock",
  "dep:thiserror",
  "dep:bitflags",
]
serde = ["dep:serde"]

[dependencies]
async-lock = { version = "3.4.2", default-features = false, optional = true }
bitflags = { version = "2.11.0", optional = true }
serde = { version = "1.0.228", optional = true, default-features = false, features = [
  "derive",
] }
thiserror = { version = "2.0.18", optional = true, default-features = false }
wgpu-types = { version = "29.0", optional = true, default-features = false }
bytemuck = { version = "1.25.0", optional = true, default-features = false, features = [
  "must_cast",
] }

[target.wasm32-unknown-unknown.dependencies]
wasm-bindgen = "0.2"
js-sys = "0.3"
wasm-bindgen-futures = "0.4"
async-lock = { version = "3.4.2", default-features = false }

[build-dependencies]
bindgen = "0.72"
cmake = "0.1.58"
syn = { version = "2.0.117", default-features = false, features = [
  "full",
  "parsing",
  "printing",
] }
prettyplease = "0.2.37"
cc = { version = "1.2", features = ["parallel"] }

[dev-dependencies]
half = { version = "2.7.1", default-features = false, features = ["bytemuck"] }
image = { version = "0.25.10", default-features = false, features = [
  "jpeg",
  "exr",
  "webp",
] }
insta = "1.47.2"

[[test]]
name = "transcoder"
path = "tests/transcoder.rs"
required-features = ["extra"]

[[test]]
name = "encoder"
path = "tests/encoder.rs"
required-features = ["extra", "encoder"]
