[workspace.package]
repository = "https://github.com/beicause/bevy_basisu_loader"
license = "MIT OR Apache-2.0"

[workspace]
members = ["crates/*", "examples/*"]
resolver = "3"

[profile.dev]
opt-level = 1

[profile.web_release]
inherits = "release"
opt-level = "s"
lto = "thin"
codegen-units = 1
panic = "abort"
