[workspace]
resolver = "3"
members = ["crates/*", "examples/*"]

[workspace.package]
repository = "https://github.com/beicause/bevy_basisu_loader"
license = "MIT OR Apache-2.0"

[workspace.dependencies]
bevy = { version = "0.19", default-features = false }

[profile.test]
opt-level = 1

[profile.web_release]
inherits = "release"
opt-level = "s"
lto = "thin"
panic = "abort"
codegen-units = 1
