[workspace]
resolver = "3"
members = ["crates/*", "examples/*"]

[workspace.package]
repository = "https://github.com/beicause/basisu_c_sys"
license = "MIT OR Apache-2.0"

[workspace.dependencies]
bevy = { version = "0.19", default-features = false }

[workspace.lints.clippy]
allow_attributes = "warn"
allow_attributes_without_reason = "warn"

[profile.test]
opt-level = 1

[profile.web_release]
inherits = "release"
opt-level = "s"
lto = "thin"
panic = "abort"
codegen-units = 1
