[package]
name = "bevy_basisu_loader"
version = "0.5.0"
edition = "2024"
repository.workspace = true
license.workspace = true
description = "Provides a lightweight, cross-platform KTX2 Basis Universal texture loader for Bevy"
keywords = ["bevy", "basis-universal", "asset", "transcoder"]
exclude = ["src/snapshots"]

[dependencies]
basisu_c_sys = { version = "0.4", features = [
  "serde",
], path = "../basisu_c_sys" }

bevy = { version = "0.18", default-features = false, features = [
  "bevy_asset",
  "bevy_image",
  "bevy_render",
  "bevy_log",
] }
serde = { version = "1", features = ["derive"] }
thiserror = { version = "2", default-features = false }
log = { version = "0.4", default-features = false }
async-lock = "3.4.2"
bitflags = "2.11.0"

[dev-dependencies]
insta = "1.47.2"
