#![doc = include_str!("../README.md")]
#![cfg_attr(docsrs, feature(doc_cfg), doc(auto_cfg = false))]
#![cfg_attr(not(feature = "std"), no_std)]

extern crate alloc;
#[cfg(test)]
extern crate std;

// Brings the vendored musl libc / libc++ and the `#[no_mangle]` libc
// forwarders into the link. It is only a dependency on the bare-metal wasm
// targets, so on every other target this import does not exist either.
#[cfg(all(target_arch = "wasm32", any(target_os = "unknown", target_os = "none"),))]
use basisu_wasm_libcxx as _;

#[cfg(feature = "extra")]
#[cfg_attr(docsrs, doc(cfg(feature = "extra")))]
pub mod extra;

/// Constants shared by the encoder and transcoder C APIs.
///
/// These mirror the `BU_*`, `BTF_*`, `TF_*`, and `DECODE_FLAGS_*` macros of
/// `basisu_wasm_api_common.h`.
pub mod common {
    #[expect(
        missing_docs,
        reason = "raw bindgen output; the C header carries no doc comments to reproduce"
    )]
    mod generated {
        include!(concat!(env!("OUT_DIR"), "/basisu_api_common.rs"));
    }
    pub use generated::*;
}

mod utils;
pub use utils::*;

/// Raw encoder C API (`bu_*`), generated by bindgen from
/// `basisu_wasm_api.h`.
///
/// These are the unwrapped entry points that take and return offsets into
/// the module linear memory. Prefer the checked wrappers in [`extra`] and the
/// enums in [`BasisTextureFormat`].
#[cfg(feature = "encoder")]
#[cfg_attr(docsrs, doc(cfg(feature = "encoder")))]
pub mod encoder {
    #[expect(
        missing_docs,
        reason = "raw bindgen output; the C header carries no doc comments to reproduce"
    )]
    mod generated {
        include!(concat!(env!("OUT_DIR"), "/basisu_c_api.rs"));
    }
    pub use generated::*;
    include!("bool32.rs");
}

/// Raw transcoder C API (`bt_*`), generated by bindgen from
/// `basisu_wasm_transcoder_api.h`.
///
/// These are the unwrapped entry points that take and return offsets into
/// the module linear memory. Prefer the checked wrappers in [`extra`] and the
/// enums in [`TranscodeTargetFormat`].
pub mod transcoder {
    #[expect(
        missing_docs,
        reason = "raw bindgen output; the C header carries no doc comments to reproduce"
    )]
    mod generated {
        include!(concat!(env!("OUT_DIR"), "/basisu_c_transcoder_api.rs"));
    }
    pub use generated::*;
    include!("bool32.rs");
}
