[package]
name = "bevy_basisu_saver"
version = "0.5.0"
edition = "2024"
description = "A bevy asset processor to transform images to basisu ktx2 textures"
repository.workspace = true
license.workspace = true
keywords = ["asset", "basis-universal", "bevy", "encoder"]

[dependencies]
basisu_c_sys = {
  path = "../basisu_c_sys",
  version = "0.8",
  default-features = false,
  features = [
    "encoder",
    "extra",
    "serde",
  ]
}
bevy_basisu_loader = {
  path = "../bevy_basisu_loader",
  version = "0.6",
  default-features = false
}

async-lock = "3.4.2"
bevy = {
  workspace = true,
  features = [
    "bevy_asset",
    "bevy_image",
    "bevy_log",
    "bevy_render",
  ]
}
log = { version = "0.4", default-features = false }
serde = { version = "1", features = ["derive"] }
thiserror = { version = "2", default-features = false }

[dev-dependencies]
bevy = {
  workspace = true,
  features = [
    "jpeg",
  ]
}
insta = "1.47.2"

[features]
default = [
  "transcode_astc",
  "transcode_etc1s_bc4_5",
  "transcode_etc1s_bc7",
  "transcode_etc1s_etc2",
  "transcode_uastc",
  "transcode_uastc_hdr",
  "transcode_xuastc",
]
transcode_astc = ["basisu_c_sys/transcode_astc"]
transcode_etc1s_bc1 = ["basisu_c_sys/transcode_etc1s_bc1"]
transcode_etc1s_bc3 = ["basisu_c_sys/transcode_etc1s_bc3"]
transcode_etc1s_bc4_5 = ["basisu_c_sys/transcode_etc1s_bc4_5"]
transcode_etc1s_bc7 = ["basisu_c_sys/transcode_etc1s_bc7"]
transcode_etc1s_etc2 = ["basisu_c_sys/transcode_etc1s_etc2"]
transcode_uastc = ["basisu_c_sys/transcode_uastc"]
transcode_uastc_hdr = ["basisu_c_sys/transcode_uastc_hdr"]
transcode_xuastc = ["basisu_c_sys/transcode_xuastc"]
