name: Rust CI

on:
  workflow_dispatch:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

concurrency:
  group: ${{github.workflow}}-${{github.ref}}
  cancel-in-progress: true

env:
  CARGO_TERM_COLOR: always
  ANDROID_NDK_VERSION: 28.1.13356709

jobs:
  build-lib:
    name: Build ${{matrix.os}}
    runs-on: ${{matrix.os}}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        include:
          - os: ubuntu-latest
            cargo-flags: --release
          - os: macos-latest
            cargo-flags:
          - os: windows-latest
            cargo-flags:

    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Install Linux dependencies
        if: ${{ matrix.os == 'ubuntu-latest' }}
        uses: ./.github/actions/install-linux-deps

      - name: Install rust toolchain
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: stable

      - name: Clippy
        run: cargo clippy -- -D warnings

      - name: Doc ${{ matrix.cargo-flags }}
        run: cargo doc --workspace --all-features --no-deps --document-private-items --keep-going ${{ matrix.cargo-flags }}
        env:
          RUSTDOCFLAGS: -D warnings

      - name: Build ${{ matrix.cargo-flags }}
        run: cargo build --workspace ${{ matrix.cargo-flags }}

      - name: Test ${{ matrix.cargo-flags }}
        run: cargo test --workspace ${{ matrix.cargo-flags }}

  build-wasm:
    name: Build wasm
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Install rust toolchain
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: stable
          targets: wasm32-unknown-unknown

      - name: Build wasm
        run: RUSTFLAGS="-Ctarget-feature=+simd128" cargo build --workspace --target wasm32-unknown-unknown

  build-android:
    name: Build android
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Install rust toolchain
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: stable
          targets: aarch64-linux-android

      - name: Install cargo-binstall
        uses: cargo-bins/cargo-binstall@v1.16.6

      - name: Install Android NDK
        run: ${ANDROID_HOME}/cmdline-tools/latest/bin/sdkmanager 'ndk;${{env.ANDROID_NDK_VERSION}}'

      - name: Install cargo-ndk
        run: cargo binstall cargo-ndk

      - name: Build
        run:
          export ANDROID_NDK_HOME=${ANDROID_HOME}/ndk/${{env.ANDROID_NDK_VERSION}} &&
          export ANDROID_NDK_ROOT=${ANDROID_NDK_HOME} &&
          cargo ndk-env -t arm64-v8a &&
          cargo ndk -t arm64-v8a -P 26 build --features bevy/android-game-activity
