name: Prebuild basisu wasm

on:
  workflow_dispatch:

concurrency:
  group: ${{github.workflow}}-${{github.ref}}
  cancel-in-progress: true

permissions:
  contents: write
  pull-requests: write

env:
  EM_VERSION: 5.0.5

jobs:
  prebuild-basisu-wasm:
    name: Prebuild basisu wasm
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: Install Emscripten
        uses: mymindstorm/setup-emsdk@v16
        with:
          version: ${{ env.EM_VERSION }}

      - name: Build vendored basisu wasm
        run: >
          pushd crates/basisu_c_sys
          && mkdir build
          && cd build
          && emcmake cmake ..
          && emmake make -j$(nproc)
          && cp ./basisu_encoder.js ../wasm/basisu_encoder.js
          && cp ./basisu_transcoder.js ../wasm/basisu_transcoder.js
          && cp ./basisu_encoder.wasm ../wasm/basisu_encoder.wasm
          && cp ./basisu_transcoder.wasm ../wasm/basisu_transcoder.wasm
          && popd

      - name: Upload artifact
        uses: actions/upload-artifact@v6
        with:
          path: crates/basisu_c_sys/wasm/

      - name: Create pull request
        uses: peter-evans/create-pull-request@v8
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: Update prebuilt basisu wasm
