# Simple workflow for deploying static content to GitHub Pages
name: Deploy static content to Pages

on:
  # Runs on pushes targeting the default branch
  # push:
  # branches: ["master"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
concurrency:
  group: "pages"
  cancel-in-progress: true

env:
  CARGO_TERM_COLOR: always
  EM_VERSION: 5.0.5

jobs:
  # Single deploy job since we're just deploying
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: Clone `basisu_c_sys_asset_files`
        run: git clone --depth 1 https://github.com/beicause/basisu_c_sys_asset_files

      - name: Install Emscripten
        uses: mymindstorm/setup-emsdk@v16
        with:
          version: ${{ env.EM_VERSION }}

      - name: Install wasm-opt
        run: wget https://github.com/WebAssembly/binaryen/releases/download/version_125/binaryen-version_125-x86_64-linux.tar.gz && tar -xvf binaryen-version_125-x86_64-linux.tar.gz && sudo cp binaryen-version_125/bin/wasm-opt /usr/local/bin/ && rm -r binaryen-version_125 && rm binaryen-version_125-x86_64-linux.tar.gz

      - name: Install cargo-binstall
        uses: cargo-bins/cargo-binstall@v1.16.6

      - name: Install rust toolchain
        run: |
          rustup toolchain install stable --profile=minimal
          rustup target add wasm32-unknown-unknown

      - name: Install wasm-bindgen
        run: cargo binstall --version ^0.2 --force wasm-bindgen-cli

      - name: Build webgpu
        run: RUSTFLAGS="-Ctarget-feature=+simd128" cargo b -p test_scene --features bevy/webgpu --target wasm32-unknown-unknown --profile web_release

      - name: Wasm bindgen webgpu
        run: wasm-bindgen --out-name test_scene --out-dir web/target/webgpu/ --target web target/wasm32-unknown-unknown/web_release/test_scene.wasm

      - name: Optimize wasm webgpu
        run: wasm-opt --enable-simd --enable-bulk-memory-opt --enable-nontrapping-float-to-int -Os ./web/target/webgpu/test_scene_bg.wasm -o ./web/target/webgpu/test_scene_bg.wasm

      - name: Setup Pages
        uses: actions/configure-pages@v6

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v5
        with:
          path: web/

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v5
