[package]
name = "test_scene"
version = "0.0.0"
edition = "2024"
publish = false

[lib]
crate-type = ["cdylib", "lib"]
name = "test_scene_lib"

[dependencies]
bevy_basisu_loader = { path = "../../crates/bevy_basisu_loader" }

log = { version = "*", features = ["release_max_level_debug"] }

bevy = {
  workspace = true,
  features = [
    # collection: dev
    #
    # "debug",
    # "bevy_dev_tools",
    # "file_watcher",

    # collection: audio
    #
    # "bevy_audio",
    # "vorbis",

    # collection: scene
    "bevy_scene",

    # collection: picking
    "bevy_picking",
    # "mesh_picking",
    # "sprite_picking",
    "ui_picking",

    "bevy_feathers",

    # collection: default_app
    "async_executor",
    "bevy_asset",
    "bevy_input_focus",
    "bevy_log",
    "bevy_state",
    "bevy_window",
    "custom_cursor",
    "reflect_auto_register",

    # collection: default_platform
    "default_font",
    "android-game-activity",
    "bevy_winit",
    "multi_threaded",
    "std",
    "sysinfo_plugin",
    "wayland",
    "webgpu",
    "x11",
    # "bevy_gilrs",
    # "webgl2",

    # collection: common_api
    "bevy_camera",
    "bevy_color",
    "bevy_image",
    "bevy_mesh",
    "bevy_shader",
    "bevy_text",

    "exr",
    "hdr",
    "jpeg",
    "png",

    # "bevy_animation",
    # "bevy_gizmos",

    "bevy_core_pipeline",
    "bevy_pbr",
    "bevy_render",
    "bevy_ui_render",
    # "bevy_post_process",
    # "bevy_sprite_render",
    # "bevy_gizmos_render",
  ]
}

[lints]
workspace = true
