[package]
name = "test_scene"
version = "0.0.0"
edition = "2024"
publish = false

[lib]
name = "test_scene_lib"
crate-type = ["lib", "cdylib"]

[dependencies]
bevy_basisu_loader = { path = "../../crates/bevy_basisu_loader" }

bevy = { version = "0.18", default-features = false, features = [
  # collection: dev
  # "debug",
  # "bevy_dev_tools",
  # "file_watcher",

  # collection: audio
  # "bevy_audio",
  # "vorbis",

  # collection: scene
  # "bevy_scene",

  # collection: picking
  # "bevy_picking",
  # "mesh_picking",
  # "sprite_picking",
  # "ui_picking",

  # collection: default_app
  "async_executor",
  "bevy_asset",
  "bevy_input_focus",
  "bevy_log",
  "bevy_state",
  "bevy_window",
  "custom_cursor",
  "reflect_auto_register",

  # collection: default_platform
  "std",
  "android-game-activity",
  # "android_shared_stdcxx",
  # "bevy_gilrs",
  "bevy_winit",
  "default_font",
  "multi_threaded",
  "webgl2",
  "x11",
  "wayland",
  "sysinfo_plugin",

  # collection: common_api
  # "bevy_animation",
  "bevy_camera",
  "bevy_color",
  # "bevy_gizmos",
  "bevy_image",
  "bevy_mesh",
  "bevy_shader",
  "bevy_text",
  # "hdr",
  # "png",

  "bevy_render",
  "bevy_core_pipeline",
  # "bevy_post_process",
  # "bevy_sprite_render",
  # "bevy_gizmos_render",
  "bevy_pbr",
  "bevy_ui_render",
] }
